import type { Metadata } from "next";
<<<<<<< ours
<<<<<<< ours
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
=======
>>>>>>> theirs
import { Inter, JetBrains_Mono as JetBrainsMono } from "next/font/google";
import "./globals.css";

const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" });
const fontMono = JetBrainsMono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: "Atlas Agent Console",
  description:
    "Operate the self-hosted search engine with a co-pilot UI that keeps you in control.",
<<<<<<< ours
>>>>>>> theirs
=======
>>>>>>> theirs
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< ours
<<<<<<< ours
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg-background font-sans antialiased ${fontSans.variable} ${fontMono.variable}`}>
>>>>>>> theirs
=======
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg-background font-sans antialiased ${fontSans.variable} ${fontMono.variable}`}>
>>>>>>> theirs
        {children}
      </body>
    </html>
  );
}
