version: "3.9"

services:
  selfsearch:
    build:
      context: .
      args:
        USE_JS_FALLBACK: ${CRAWLER_USE_JS_FALLBACK:-true}
    image: selfsearch:latest
    environment:
      UI_PORT: ${UI_PORT:-5000}
      INDEX_DIR: ${INDEX_DIR:-/app/data/index}
      CRAWL_STORE: ${CRAWL_STORE:-/app/data/crawl}
    ports:
      - "${UI_PORT:-5000}:${UI_PORT:-5000}"
    volumes:
      - ./data:/app/data
    command: ["python", "app.py"]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os,urllib.request; port=os.environ.get('UI_PORT','5000'); urllib.request.urlopen('http://127.0.0.1:' + port + '/healthz')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
